"""Initial migration

Revision ID: 431754198914
Revises: 
Create Date: 2026-04-11 08:19:23.841394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '431754198914'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_change_detection_id'), 'change_detection', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_id'), 'compliance', ['id'], unique=False)
    op.drop_index('idx_images_project', table_name='images')
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_project_id'), 'images', ['project_id'], unique=False)
    op.drop_index('idx_indices_image', table_name='indices')
    op.create_index(op.f('ix_indices_id'), 'indices', ['id'], unique=False)
    op.create_index(op.f('ix_indices_image_id'), 'indices', ['image_id'], unique=False)
    op.alter_column('projects', 'aoi_geojson',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('projects', 'aoi_geojson',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_indices_image_id'), table_name='indices')
    op.drop_index(op.f('ix_indices_id'), table_name='indices')
    op.create_index('idx_indices_image', 'indices', ['image_id'], unique=False)
    op.drop_index(op.f('ix_images_project_id'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.create_index('idx_images_project', 'images', ['project_id'], unique=False)
    op.drop_index(op.f('ix_compliance_id'), table_name='compliance')
    op.drop_index(op.f('ix_change_detection_id'), table_name='change_detection')
    # ### end Alembic commands ###
